HW6 is completed
kryakozyablik/otus_hw_go pull request #6
Opened 2020-09-06 07:23 UTC by kryakozyablik

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-09-06 13:04 UTC, kulti requested changes
В текущем решении done останавливает только горутину ExecutePipeline. Горутины внутри стейджей продолжат работу и навсегда зависнут на записи в канал.

Еще нужно подтянуть master: This branch is out-of-date with the base branch

2020-09-07 20:55 UTC, kryakozyablik commented
@kulti Поправил код. Подключал goleak для детектирования зависших горутин, но пришлось выпилить т.к. начали детектироваться горутины из теста. (висят на запись после Done-сигнала)

2020-09-08 17:35 UTC, kulti requested changes

2020-09-08 17:35 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +	}()
Эта горутина поможет остановить только первый стейдж — закроется канал, из которого он читает, и цикл чтения завершится. А вот все другие стейджи продолжат висеть.

Нужно немного доработать решение.

2020-09-11 08:00 UTC, kulti approved these changes
Теперь все ок. Думаю, ради интереса можно попробовать вернуть goleak.

ДЗ принято - 10/10.

2020-09-14 19:38 UTC, merged